import "./globals.css";
import { Providers } from "./redux/provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Climate App</title>
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
